// Core Actions
const coreActions = {
  VIS_CONFIG_COMPILED: 'VIS_CONFIG_COMPILED',
  FILTER_DATA: 'FILTER_DATA',
  SET_CALLBACKS: 'SET_CALLBACKS',
  MARK_SELECTED: 'MARK_SELECTED',
  SET_SELECTION: 'SET_SELECTION',
  SET_FILTERS: 'SET_FILTERS',
  SET_ADDITIONAL_FILTERS: 'SET_ADDITIONAL_FILTERS',
  SET_OPTIONS: 'SET_OPTIONS'
};

export default {
  ...coreActions
};
